name: Bot Informativo AACEP

on:
  schedule:
    - cron: "0 19 * * 1-5"  # Segunda a sexta às 19h UTC
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar scraper
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SENHA_EMAIL: ${{ secrets.SENHA_EMAIL }}
          EMAIL_REMENTENTE: ${{ secrets.EMAIL_REMENTENTE }}
          EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
        run: python bot_notificador.py
